language: ruby
cache: bundler
os: linux
dist: xenial
addons:
  firefox: latest
env:
  - MOZ_HEADLESS=1
services:
  - xvfb
  - mysql

before_install:
  - "export TZ=America/New_York"
  - sudo apt-get -y install wget build-essential libc6-dev
  - wget http://www.freetds.org/files/stable/freetds-1.1.24.tar.gz -O /tmp/freetds.tar.gz
  - pushd /tmp && tar -xzvf /tmp/freetds.tar.gz
  - cd freetds-1.1.24 && ./configure --prefix=/usr/local --with-tdsver=7.3 && make && sudo make install && popd
before_script:
  - "export DISPLAY=:99.0"
  - cp config/database.yml.example config/database.yml
  - cp dotenv.example .env
  - mysql -e 'create database rmid_test;'
  - RAILS_ENV=test bundle exec rake db:schema:load
  - rvm use $(< .ruby-version) --install --binary --fuzzy
  - export BUNDLE_GEMFILE=$PWD/Gemfile
  - RAILS_ENV=test bundle exec rake assets:precompile
jobs:
  include:
    - script:
      - bundle exec rspec spec/controllers
      - bundle exec rspec spec/mailers
      - bundle exec rspec spec/models
      - bundle exec rspec spec/requests
      - bundle exec rspec spec/system
