default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  variables:
    sql_mode: TRADITIONAL
development:
  <<: *default
  database: rmid_development
test:
  <<: *default
  database: rmid_test

