development:
  adapter: mysql2
  encoding: utf8
  username: sparc_test
  password: SP@rC_fULF!ll
  port: 3306
  timeout: 5000
  pool: 5
  host: bmic-dbphi-s.ccit.musc.edu
  database: sparc_request_testing

